// AUTO-GENERATED by scripts/gen-trap-art-manifest.mjs — do not edit by hand.
// Trap / affliction ids with an icon at public/assets/traps/{id}.webp, loaded as
// 'trap-art-{id}' in BootScene. Regenerate with: npm run gen:trap-art
export const TRAP_ART_IDS: readonly string[] = [
  "affliction_bleed",
  "affliction_burn",
  "affliction_fear",
  "affliction_poison",
  "affliction_shock",
  "affliction_slow",
  "dokkaebi_fire",
  "dread_gas",
  "ember_chain",
  "ember_trap",
  "fear_trap",
  "hellmouth",
  "lightning_net",
  "plague_tide",
  "poison_trap",
  "quagmire",
  "slow_trap",
  "spike_trap",
  "storm_cage",
  "stun_trap",
  "thorn_wall",
  "wildfire_pit"
];
