// AUTO-GENERATED by scripts/gen-trap-art-manifest.mjs — do not edit by hand.
// Trap / affliction ids with an icon at public/assets/traps/{id}.webp, loaded as
// 'trap-art-{id}' in BootScene. Regenerate with: npm run gen:trap-art
export const TRAP_ART_IDS: readonly string[] = [];
